# Generated by Django 2.1.5 on 2019-02-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tarefa', models.CharField(max_length=100)),
                ('descricao_tarefa', models.CharField(max_length=500)),
                ('data_tarefa', models.DateTimeField()),
            ],
        ),
    ]
